name: Docs

on:
  push:
    branches:
      - development
    paths:
      - 'docs/**'
      - 'examples/**'
      - '**/api.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache-dependency-path: '**/config/rush/pnpm-lock.yaml'
          registry-url: https://registry.npmjs.org/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Update Autoinstallers
        run: |
          node common/scripts/install-run-rush.js update-autoinstaller --name doc-tools
          node common/scripts/install-run-rush.js update-autoinstaller --name rush-plugins
          node common/scripts/install-run-rush.js update-autoinstaller --name rush-prettier

      - name: Rush Build
        run: node common/scripts/install-run-rush.js rebuild --verbose

      - name: Build Histoire Stories + Vitepress
        working-directory: ./docs
        run: node ../common/scripts/install-run-rushx.js build:full

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/.vitepress/dist

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
