name: Linters
# https://github.com/marketplace/actions/prettier-check
# This action works with pull requests and pushes on the main branch
on:
  pull_request:
  push:
    branches: [development]

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Prettier
        id: prettier-run
        uses: rutajdash/prettier-cli-action@v1.0.0
        with:
          config_path: ./.prettierrc.js
          ignore_path: ./.prettierignore

      # This step only runs if prettier finds errors causing the previous step to fail
      # This steps lists the files where errors were found
      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{steps.prettier-run.outputs.prettier_output}}"

  sort-package-json:
    name: Sort package.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Install Node.js
        with:
          cache-dependency-path: '**/config/rush/pnpm-lock.yaml'
          registry-url: https://npm.pkg.github.com/

      - name: Install Rush
        run: node common/scripts/install-run-rush.js install

      - name: Sort package.json
        run: node common/scripts/install-run-rush.js sort-package-json
